<!DOCTYPE html>
<html>
<head>
    <title>Inventory Report</title>
    <style>
        /* Pengaturan Font & Dasar */
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color: #333; }
        
        /* Bagian Judul Utama */
        .title-section { text-align: center; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 2px solid #4F46E5; }
        .title-section h2 { margin: 0; font-size: 20px; color: #1E293B; letter-spacing: 1px; }
        
        /* Tabel Informasi/Metadata (Tanpa Garis) */
        .info-table { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
        .info-table td { padding: 4px 0; border: none; }
        .info-label { font-weight: bold; color: #64748b; width: 110px; }
        
        /* Tabel Data Utama */
        .data-table { width: 100%; border-collapse: collapse; }
        .data-table th, .data-table td { border: 1px solid #cbd5e1; padding: 8px; }
        
        /* Header Tabel warna Indigo (Sesuai Excel) */
        .data-table th { background-color: #4F46E5; color: #ffffff; text-transform: uppercase; font-size: 11px; text-align: center; }
        
        /* Zebra-striping (Baris selang-seling warna abu-abu agar mudah dibaca) */
        .data-table tbody tr:nth-child(even) { background-color: #f8fafc; }
        
        /* Baris Grand Total */
        .total-row td { background-color: #f1f5f9; font-weight: bold; color: #1E293B; font-size: 13px; }
        
        /* Utility Classes */
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .unit-text { font-size: 10px; color: #64748b; font-weight: normal; }
    </style>
</head>
<body>

    <div class="title-section">
        <h2>MONTHLY INVENTORY REPORT</h2>
    </div>

    <table class="info-table">
        <tr>
            <td class="info-label">Site / Location</td>
            <td>: <strong>IBP</strong></td>
            <td class="info-label text-right" style="padding-right: 10px;">Report Period</td>
            <td>: {{ $formattedMonth }}</td>
        </tr>
        <tr>
            <td class="info-label">Generated By</td>
            <td>: {{ auth()->user()->first_name ?? 'System Admin' }}</td>
            <td class="info-label text-right" style="padding-right: 10px;">Downloaded At</td>
            <td>: {{ now()->format('d M Y, H:i') }} WIB</td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="30%">Item Name</th>
                <th width="15%">Part Number</th>
                <th width="20%">Category</th>
                <th width="15%">Stock</th>
                <th width="15%">Damaged/Defect</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $index => $item)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $item->item_name }}</td>
                <td class="text-center">{{ $item->part_number ?? '-' }}</td>
                <td class="text-center">{{ $item->category->category_name ?? '-' }}</td>
                <td class="text-center font-bold">
                    {{ $item->stock }} <span class="unit-text">{{ $item->units ?? 'pcs' }}</span>
                </td>
                <td class="text-center" style="{{ $item->damaged_stock > 0 ? 'color: #e11d48; font-weight: bold;' : '' }}">
                    {{ $item->damaged_stock ?? 0 }}
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="4" class="text-right" style="padding-right: 15px;">GRAND TOTAL :</td>
                <td class="text-center">{{ $items->sum('stock') }}</td>
                <td class="text-center">{{ $items->sum('damaged_stock') }}</td>
            </tr>
        </tfoot>
    </table>

</body>
</html>